### ISSUE TITLE
Something wrong with pictures

### ISSUE THREAD

**Issue by ivankozlov** [fedecalendino/alfred-crypto-prices#1]
<img width="710" alt="SCR-20230202-qbd" src="https://user-images.githubusercontent.com/1015311/216423148-dac59fa1-53c6-4fc7-abf5-80e6cba28c5a.png">

**Comment by fedecalendino** [comment]
It seems that is missing the cache folder. I'll try to fix it as soon as I can. 

In the meantime, you can check the debug menu of alfred to see exactly what is the path that is missing and create it your self.

**Comment by fedecalendino** [comment]
Hi @ivankozlov !

It should be fixed on the latest version: https://github.com/fedecalendino/alfred-crypto-prices/releases/tag/v1.8.4

Let me know it that works for you.

Fede.

**Comment by ivankozlov** [comment]
Works great, thank you! ❤️
